fix: rearm workflow

diff --git a/.github/workflows/rearm.yml b/.github/workflows/rearm.yml
--- a/.github/workflows/rearm.yml
+++ b/.github/workflows/rearm.yml
@@ -6,8 +6,52 @@ on:
     branches: [ main ]
 
 jobs:
+  setup:
+    name: Determine Project Version
+    runs-on: ubuntu-latest
+    outputs:
+      sanitized_project_version: ${{ steps.setversion.outputs.sanitized_project_version }}
+    
+    steps:
+        - name: Checkout (with tags)
+          uses: actions/checkout@v4
+          with:
+            fetch-depth: 0
+            fetch-tags: true
+        
+        - name: Set Project Version
+          id: setversion
+          shell: bash
+          run: |
+            echo "GITHUB_REF=${GITHUB_REF}"
+            echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
+
+            LATEST_TAG=$(git tag --list 'v*' --sort=-v:refname | head -n 1)
+
+            if [[ -z "$LATEST_TAG" ]]; then
+              echo "No version tags found (vX.Y.Z required)"
+              exit 1
+            fi
+
+            BASE_VERSION="${LATEST_TAG#v}"
+
+            if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
+              VERSION="${GITHUB_REF_NAME#v}"
+            elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
+              VERSION="${BASE_VERSION}-main-${GITHUB_RUN_NUMBER}"
+            else
+              VERSION="${BASE_VERSION}-dev-${GITHUB_RUN_NUMBER}"
+            fi
+
+            echo "Resolved project version: ${VERSION}"
+            echo "sanitized_project_version=${VERSION}" >> "$GITHUB_OUTPUT"
+
+            echo "Final output:"
+            cat "$GITHUB_OUTPUT"
+
   sign-with-rearm:
     name: ReARM - Generate, Sign & Send
+    needs: setup
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repo
@@ -31,13 +75,14 @@ jobs:
           rearm_api_key: ${{ secrets.REARM_COMPONENT_API_KEY }}
           rearm_api_url: ${{ vars.REARM_API_URL }}
           component: ${{ vars.REARM_COMPONENT_ID }}
+          version: ${{ needs.setup.outputs.sanitized_project_version }}
 
       - name: Generate and sign SBOMs
         id: sbom
         uses: relizaio/rearm-actions/sbom-sign-scan@main
         with:
-          rearm_short_version: ${{ steps.init.outputs.short_version }}
-          rearm_full_version: ${{ steps.init.outputs.full_version }}
+          #rearm_short_version: ${{ steps.init.outputs.short_version }}
+          #rearm_full_version: ${{ steps.init.outputs.full_version }}
           enable_sbom: true
           deliverable_type: FILE
           source_code_sbom_type: other
@@ -45,6 +90,8 @@ jobs:
           securesbom_host: ${{ vars.SECURE_SBOM_API_URL }}
           securesbom_pub_key_id: ${{ secrets.SECURE_SBOM_KEYID }}
           securesbom_api_key: ${{ secrets.SECURE_SBOM_API_KEY }}
+          rearm_short_version: ${{ needs.setup.outputs.sanitized_project_version }}
+          rearm_full_version: ${{ needs.setup.outputs.sanitized_project_version }}
 
       - name: Submit metadata to ReARM and Finalize
         uses: relizaio/rearm-actions/finalize@main
@@ -54,8 +101,8 @@ jobs:
           rearm_api_url: ${{ vars.REARM_API_URL }}
           component: ${{ vars.REARM_COMPONENT_ID }}
           rearm_build_start: ${{ steps.init.outputs.build_start }}
-          rearm_short_version: ${{ steps.init.outputs.short_version }}
-          rearm_full_version: ${{ steps.init.outputs.full_version }}
+          #rearm_short_version: ${{ steps.init.outputs.short_version }}
+          #rearm_full_version: ${{ steps.init.outputs.full_version }}
           rearm_build_lifecycle: 'DRAFT'
           deliverable_type: 'FILE'
           commit_list: ${{ steps.init.outputs.commit_list }}
@@ -64,3 +111,5 @@ jobs:
           sce_commit_date: ${{ steps.init.outputs.sce_commit_date }}
           sce_vcs_uri: ${{ steps.init.outputs.sce_vcs_uri }}
           scearts: ${{ steps.sbom.outputs.scearts }}
+          rearm_short_version: ${{ needs.setup.outputs.sanitized_project_version }}
+          rearm_full_version: ${{ needs.setup.outputs.sanitized_project_version }}
